# Generated by Django 4.0 on 2022-01-13 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('Laptop', 'Laptop'), ('Smartphone', 'Smartphone'), ('Camera', 'Camera')], max_length=100)),
                ('product_company', models.CharField(choices=[('HP', 'HP'), ('LENOVO', 'LENOVO'), ('DELL', 'DELL'), ('NIKON', 'NIKON'), ('CANON', 'CANON'), ('MI', 'MI'), ('APPLE', 'APPLE')], max_length=100)),
                ('product_model', models.CharField(max_length=100)),
                ('product_desc', models.TextField()),
                ('product_price', models.PositiveIntegerField()),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
